/**
 * Generates AI-FACTS.yml - the input the ai-visibility-kit reads - by importing
 * src/config/site.ts directly.
 *
 * Why it imports the TypeScript rather than re-typing the values: site.ts is
 * already the single source for the seller, the two branch addresses, the
 * WhatsApp number and the marketplace URLs, and its own comment warns that a
 * "tidied up" address stops matching the Google listing. Node 24 strips types on
 * import, so the generator reads the same module the pages and the schema read
 * and no address exists twice.
 *
 * Only prose that lives nowhere else - the definition sentence, the page map,
 * the Q&A, the agent actions - is written here.
 *
 * Usage: node scripts/ai/facts-sync.mjs [--check]
 *   --check  fails instead of writing when AI-FACTS.yml has drifted from site.ts.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const CHECK = process.argv.includes('--check');

const S = await import(new URL('../../src/config/site.ts', import.meta.url).href);
const {
  SITE_URL, SITE_NAME, BRAND_SELLER, BRAND_SELLER_AR, BRAND_SELLER_URL,
  SHOPEE_URL, TIKTOK_SHOP_URL, BRANCHES, INSTAGRAM_URL, FACEBOOK_URL,
  WHATSAPP_NUMBER, WHATSAPP_URL,
} = S;

const TODAY = '2026-08-18';
const WHATSAPP_DISPLAY = '+60 11-1111 9912';

/** One-line YAML scalar: the kit's parser has no block scalars. */
const one = s => String(s).replace(/\s*\n\s*/g, ' ').trim();

const L = [];
const p = (...lines) => L.push(...lines);

p('####################################################################');
p('#  AI-FACTS.yml - SUBUR Honey (suburhoney.com)');
p('#');
p('#  GENERATED by scripts/ai/facts-sync.mjs - do not hand-edit.');
p('#  The seller, both branch addresses, the WhatsApp number and the');
p('#  marketplace URLs are imported from src/config/site.ts, the same module');
p('#  the pages and the JSON-LD read. Change one there and re-run.');
p('#');
p('#  HARD RULES carried over from the FORGE pass (FORGE-SPEC.md):');
p('#   - Traditional-use framing only. No medical or therapeutic verb, in any');
p('#     language. Fertility vocabulary belongs in keyword lists, never in a');
p('#     claim about this product.');
p('#   - No rating, no customer count. A fabricated 5.0/5000 aggregateRating and');
p('#     its prose twin were removed sitewide; do not let either back in.');
p('#   - Honey is a bee product. Never "vegan".');
p('#   - Owner-supplied facts are exactly: the two addresses, the WhatsApp');
p('#     number, the Shopee URL and the TikTok URL. Everything else is unverified');
p('#     and stays out.');
p('####################################################################');
p('');

p('site:');
p(`  name: ${SITE_NAME}`);
/* The briefs head themselves "Madu SUBUR (SUBUR Honey)" and
   "عسل سوبور (SUBUR Honey)" - keep the same forms so a language file's heading
   never disagrees with the body under it. */
p(`  name_ms: Madu SUBUR (${SITE_NAME})`);
p(`  name_ar: عسل سوبور (${SITE_NAME})`);
p(`  url: ${SITE_URL}`);
p(`  definition: ${one(`${SITE_NAME} is a raw honeycomb blend of ten named ingredients, sold in Malaysia
   through ${BRAND_SELLER}. It is sold as a food eaten daily, not as a supplement and not as a
   medicine - a spoonful in the morning - and makes no medical claim of any kind. There are four ways
   to buy it: the ${BRANCHES.length} ${BRAND_SELLER} shops in Selangor
   (${BRANCHES.map(b => b.area).join(' and ')}), the store's own Shopee storefront and its TikTok
   Shop. WhatsApp ${WHATSAPP_DISPLAY} is a contact line, not a purchase channel.`)}`);
p(`  definition_ms: ${one(`${SITE_NAME} ialah adunan madu sarang mentah dengan sepuluh bahan bernama,
   dijual di Malaysia melalui ${BRAND_SELLER}. Ia dibawakan dalam kerangka penggunaan tradisional
   madu Timur Tengah - satu sudu pada waktu pagi - tanpa sebarang dakwaan perubatan. Ada empat cara
   untuk membelinya: ${BRANCHES.length} kedai ${BRAND_SELLER} di Selangor
   (${BRANCHES.map(b => b.area).join(' dan ')}), storefront Shopee milik kedai itu, dan TikTok Shopnya.
   WhatsApp ${WHATSAPP_DISPLAY} ialah talian pertanyaan, bukan saluran pembelian.`)}`);
p(`  definition_ar: ${one(`${SITE_NAME} خليط عسل شمعي خام من عشرة مكوّنات مذكورة بالاسم، يُباع في ماليزيا
   عبر ${BRAND_SELLER_AR}. يُقدَّم ضمن إطار الاستعمال التقليدي لخلطات العسل في الشرق الأوسط - ملعقة في
   الصباح - دون أي ادعاء طبي. وهناك أربع طرق لشرائه: متجرا ${BRAND_SELLER_AR} في سلانجور
   (${BRANCHES.map(b => b.area).join(' و')})، ومتجر شوبي التابع للمتجر نفسه، ومتجره على تيك توك.
   أما واتساب ${WHATSAPP_DISPLAY} فهو خط تواصل لا قناة شراء.`)}`);
p('  category: Raw honeycomb blend - a food, not a supplement and not a medicine');
p('  category_ms: Adunan madu sarang mentah - makanan dalam kerangka penggunaan tradisional, bukan suplemen dan bukan ubat');
p('  category_ar: خليط عسل شمعي خام - غذاء ضمن إطار الاستعمال التقليدي، وليس مكمّلاً ولا دواءً');
p(`  serving_area: ${one(`Malaysia - in person at the ${BRANCHES.length} ${BRAND_SELLER} shops in Selangor
   (${BRANCHES.map(b => b.area).join(' and ')}), plus the store's own Shopee and TikTok Shop storefronts`)}`);
p(`  serving_area_ms: ${one(`Malaysia - di ${BRANCHES.length} kedai ${BRAND_SELLER} di Selangor
   (${BRANCHES.map(b => b.area).join(' dan ')}), serta storefront Shopee dan TikTok Shop milik kedai itu`)}`);
p(`  serving_area_ar: ${one(`ماليزيا - حضورياً في متجرَي ${BRAND_SELLER_AR} في سلانجور
   (${BRANCHES.map(b => b.area).join(' و')})، إضافة إلى متجرَي المتجر على شوبي وتيك توك`)}`);
p('  audience: Households in Malaysia buying a spiced honeycomb blend, and the Arab and Malay communities in the Klang Valley');
p('  audience_ms: Isi rumah di Malaysia yang mencari adunan madu Timur Tengah, serta komuniti Arab dan Melayu di Lembah Klang');
p('  audience_ar: الأسر في ماليزيا الباحثة عن خلطة عسل شرق أوسطية، والجاليتان العربية والملايوية في وادي كلانج');
p('  tagline: A raw honeycomb blend of ten ingredients');
p('  default_language: en');
p('  languages:');
p('    - code: en');
p('      name: English');
p('    - code: ar');
p('      name: العربية');
p('      path: ar');
p('    - code: ms');
p('      name: Bahasa Melayu');
p('      path: ms');
p(`  updated: ${TODAY}`);
p('');

/* Every field here stays blank on purpose. The FORGE pass removed a fabricated
   rating and customer count; there is no certificate, registration or verified
   statistic in owner-supplied material, and inventing one would undo that work. */
p('trust:');
p('  registration:');
p('  licences:');
p('  certifications:');
p('  stats:');
p('');

p('contact:');
p(`  phone: ${WHATSAPP_DISPLAY}`);
p('');

p('address:');
p(`  street: ${BRANCHES[0].street}`);
p(`  city: ${BRANCHES[0].locality}`);
p(`  postcode: ${BRANCHES[0].postcode}`);
p('  country: Malaysia');
p('');

p('identities:');
p('  - name: WhatsApp');
p(`    url: ${WHATSAPP_URL}`);
p(`  - name: ${BRAND_SELLER}`);
p(`    url: ${BRAND_SELLER_URL}`);
p('  - name: Shopee');
p(`    url: ${SHOPEE_URL}`);
p('  - name: TikTok Shop');
p(`    url: ${TIKTOK_SHOP_URL}`);
p('  - name: Instagram');
p(`    url: ${INSTAGRAM_URL}`);
p('  - name: Facebook');
p(`    url: ${FACEBOOK_URL}`);
p('');

p('sections:');
p('  - title: Main pages');
p('    links:');
p('      - title: Home');
p('        url: /en/');
p('        description: The product, its ten ingredients, the morning ritual, wholesale enquiry and FAQ.');
p('      - title: Benefits');
p('        url: /en/benefits/');
p('        description: What each of the ten ingredients is, and why it is in the jar.');
p('      - title: Retail');
p('        url: /en/retail/');
p('        description: Every way to buy - both shops, the Shopee storefront and the TikTok Shop.');
p('      - title: Why Us');
p('        url: /en/why-us/');
p('        description: What separates this from a typical processed honey blend.');
p('      - title: Contact');
p('        url: /en/contact/');
p('        description: How to reach SUBUR Honey and the store behind it.');
p('      - title: Guides');
p('        url: /en/blog/');
p('        description: Buying guides written for Malaysian readers.');
p('  - title: Machine-readable briefs');
p('    links:');
p('      - title: English brief');
p('        url: /llms.txt');
p('        description: The product, the ingredients, the store, the search intents and 25-30 Q&A.');
p('      - title: Arabic brief');
p('        url: /llms-ar.txt');
p('        description: Researched natively for Arabic search in Malaysia - store-led, with Gulf, Levantine and Egyptian phrasing.');
p('      - title: Bahasa Melayu brief');
p('        url: /llms-ms.txt');
p('        description: Researched natively for Malay search - khasiat, madu asli vs palsu, and the local buying questions.');
p('');

/* No price is published anywhere on this site and none was supplied. */
p('pricing:');
p(`pricing_notes: ${one(`No price is published on this site, in any currency. Current pricing is on the
   ${BRAND_SELLER} Shopee storefront (${SHOPEE_URL}) and its TikTok Shop (${TIKTOK_SHOP_URL}), or by
   asking at either shop. WhatsApp ${WHATSAPP_DISPLAY} is a contact line, not an order channel.`)}`);
p('');

const FAQ = [
  ['What is SUBUR Honey?',
   `A raw honeycomb blend of ten named ingredients, sold in Malaysia through ${BRAND_SELLER}. It is a food, and it makes no medical claim.`],
  ['Where can I buy it in Malaysia?',
   `Four ways, all of them ${BRAND_SELLER}: the shop at ${BRANCHES[0].full}; the shop at ${BRANCHES[1].full}; the store's Shopee storefront at ${SHOPEE_URL}; and its TikTok Shop at ${TIKTOK_SHOP_URL}.`],
  ['Are the Shopee and TikTok listings a different seller?',
   `No. Both storefronts belong to ${BRAND_SELLER} - "arabianvillagemalaysia" is the store's own marketplace trading name, not a third-party reseller.`],
  ['Can I order over WhatsApp?',
   `WhatsApp ${WHATSAPP_DISPLAY} is a contact line for questions, not a purchase channel. Buy at either shop or through the store's two storefronts.`],
  ['How much does it cost?',
   `No price is published on this site. Current pricing is on the Shopee and TikTok Shop listings, or ask at either shop.`],
  ['How many shops are there?',
   `Two, both in Selangor: ${BRANCHES.map(b => b.area).join(' and ')}. The site once said "stores across Malaysia" - that was wrong and has been corrected.`],
  ['What is in it?',
   `Ten named ingredients blended with raw honeycomb. The Benefits page lists each one and what it is there for.`],
  ['Is it vegan?',
   `No. Honey is a bee product, and no mainstream vegan standard admits it. Any claim otherwise on an older version of this site was wrong and has been removed.`],
  ['Is it a medicine or a treatment for anything?',
   `No. It is a food. Nothing on this site claims it prevents, treats or cures any condition, and any language about long-standing use should be read as exactly that.`],
  ['Does it have a customer rating?',
   `Not one this site publishes. An earlier version carried a 5.0 rating and a "5,000 customers" line that were not real; both were removed rather than re-sourced.`],
  ['How is it usually taken?',
   `It is commonly described as a spoonful in the morning. That is a serving habit, not a dosage instruction.`],
  ['Do you ship outside the Klang Valley?',
   `Both shops are in Selangor. Orders placed through the Shopee storefront or the TikTok Shop are fulfilled and tracked inside those platforms in the normal way.`],
];
p('faq:');
for (const [q, a] of FAQ) {
  p(`  - q: ${one(q)}`);
  p(`    a: ${one(a)}`);
}
p('');

p('agent_actions:');
p('  - action: Buy online');
p(`    url: ${SHOPEE_URL}`);
p('    method: External marketplace storefront');
p(`    notes: ${one(`Shopee and TikTok Shop (${TIKTOK_SHOP_URL}) are both ${BRAND_SELLER}'s own
   storefronts, not separate sellers. Checkout, payment and tracking happen inside those platforms -
   this site has no cart.`)}`);
p('  - action: Buy in person');
p(`    url: ${SITE_URL}/en/retail/`);
p('    method: Visit a shop');
p(`    notes: ${one(BRANCHES.map(b => b.full).join(' · '))}`);
p('  - action: Ask a question');
p(`    url: ${WHATSAPP_URL}`);
p('    method: WhatsApp message');
p(`    notes: ${one(`A contact line, not an order channel. Nothing is sold or reserved over WhatsApp.`)}`);
p('  - action: Read the full machine-readable brief');
p('    url: /llms.txt');
p('    method: GET');
p(`    notes: ${one(`English at /llms.txt, Arabic at /llms-ar.txt, Bahasa Melayu at /llms-ms.txt. Each
   is researched for its own market rather than translated, so the three do not mirror each other.`)}`);
p('');

p('ops:');
p('  sitemap: /sitemap.xml');
p('  indexnow_key:');
p('  blocked_paths:');

const text = L.join('\n') + '\n';
const OUT = join(ROOT, 'AI-FACTS.yml');

/* Carry a committed IndexNow key forward - it is generated once and has to keep
   matching the key file served at the web root. [ \t] not \s: \s matches the
   newline, and an empty value then captures the next line's key name. */
let final = text;
if (existsSync(OUT)) {
  const m = readFileSync(OUT, 'utf8').match(/^[ \t]*indexnow_key:[ \t]*(\S+)[ \t]*$/m);
  if (m) final = text.replace('  indexnow_key:\n', `  indexnow_key: ${m[1]}\n`);
}

if (CHECK) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== final) {
    console.error('\n  AI-FACTS.yml is stale - src/config/site.ts or the overlay changed.');
    console.error('  Run: node scripts/ai/facts-sync.mjs\n');
    process.exit(1);
  }
  console.log('  AI-FACTS.yml is in sync with src/config/site.ts');
} else {
  writeFileSync(OUT, final, 'utf8');
  console.log(`  wrote AI-FACTS.yml (${(Buffer.byteLength(final) / 1024).toFixed(1)} KB) from src/config/site.ts`);
}
